	-- SUPPLY -- 


NDefines.NSupply.INFRA_TO_SUPPLY = 0.5  -- 0.3
NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.22 --0.2
NDefines.NSupply.VP_TO_SUPPLY_BONUS_CONVERSION = 0.065 --0.05

NDefines.NSupply.CAPITAL_SUPPLY_BASE = 10.0 -- 5.0
NDefines.NSupply.CAPITAL_SUPPLY_CIVILIAN_FACTORIES = 0.4 -- 0.3
NDefines.NSupply.CAPITAL_SUPPLY_MILITARY_FACTORIES = 0.65 -- 0.6
NDefines.NSupply.CAPITAL_SUPPLY_DOCKYARDS = 0.7 -- 0.4

NDefines.NSupply.CAPITAL_INITIAL_SUPPLY_FLOW = 6.0 -- 5.0
NDefines.NSupply.CAPITAL_STARTING_PENALTY_PER_PROVINCE = 0.5 -- 0.5
NDefines.NSupply.CAPITAL_ADDED_PENALTY_PER_PROVINCE = 1.2 -- 1.2
NDefines.NSupply.NODE_INITIAL_SUPPLY_FLOW = 3.6 -- 2.8
NDefines.NSupply.NODE_STARTING_PENALTY_PER_PROVINCE = 0.50 -- 0.50
NDefines.NSupply.NODE_ADDED_PENALTY_PER_PROVINCE = 1.0 -- 0.70
NDefines.NSupply.NAVAL_BASE_INITIAL_SUPPLY_FLOW = 4.0 -- 3.5
NDefines.NSupply.NAVAL_BASE_STARTING_PENALTY_PER_PROVINCE = 0.8 -- 0.8
NDefines.NSupply.NAVAL_BASE_ADDED_PENALTY_PER_PROVINCE = 1.5 --1.0

NDefines.NSupply.FLOATING_HARBOR_BASE_SUPPLY = 30 -- 15
NDefines.NSupply.FLOATING_HARBOR_BASE_DURATION = 45 -- 21
NDefines.NSupply.FLOATING_HARBOR_INITIAL_SUPPLY_FLOW = 3 -- 2.6
NDefines.NSupply.FLOATING_HARBOR_STARTING_PENALTY_PER_PROVINCE = 0.8 -- 0.8
NDefines.NSupply.FLOATING_HARBOR_ADDED_PENALTY_PER_PROVINCE = 0.8 -- 0.8


NDefines.NSupply.SUPPLY_FLOW_DROP_REDUCTION_AT_MAX_INFRA = 0.60 -- 0.30

NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_BONUS = 3.0 -- 2.2

NDefines.NSupply.RAILWAY_BASE_FLOW = 10.0 -- 10.0
NDefines.NSupply.RAILWAY_FLOW_PER_LEVEL = 7 --5.0
NDefines.NSupply.RAILWAY_FLOW_PENALTY_PER_DAMAGED = 10 -- 5.0


NDefines.NSupply.NODE_FLOW_BONUS_PER_RAIL_LEVEL = 0.6 -- 0.34


NDefines.NSupply.NAVAL_BASE_FLOW = 16.0 -- 15.0
NDefines.NSupply.NAVAL_FLOW_PER_LEVEL = 6.0 --5.0


NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 20 --15
NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.1 --0.3
NDefines.NSupply.SUPPLY_DISRUPTION_DAILY_RECOVERY = 3.0

NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN = 3  -- vilkata defines , was 5
NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN_CORE = 2  -- vilkata defines , was 4

NDefines.NSupply.RAILWAY_FLOW_PENALTY_PER_DAMAGED = 4.9